previews:
  generation: automatic

services:
  - type: web
    name: client
    runtime: node
    repo: https://github.com/notprowler/web103_finalproject_Centsible/tree/main/client # Replace with your actual repo URL
    buildCommand: npm install && npm run build
    startCommand: npm run dev
    envVars:
      - key: VITE_API_URL
        value: https://api.yourdomain.com # Replace with your actual API URL

  - type: web
    name: server
    runtime: node
    repo: https://github.com/notprowler/web103_finalproject_Centsible/tree/main/server # Replace with your actual repo URL
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: PGUSER
        value: postgres # Replace with your actual PostgreSQL user
      - key: PGPASSWORD
        value: vFOeoEJIEbJngQWLfskbGhRhKOzjryuW # Replace with your actual PostgreSQL password
      - key: PGHOST
        value: autorack.proxy.rlwy.net # Replace with your actual PostgreSQL host
      - key: PGDATABASE
        value: railway # Replace with your actual PostgreSQL database
      - key: PGPORT
        value: 17289 # Replace with your actual PostgreSQL port
      - key: PGSSLMODE
        value: require 

databases:
  - name: mydatabase
    plan: starter
    diskSizeGB: 10
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all IPs

envVarGroups:
  - name: my-env-group
    envVars:
      - key: API_BASE_URL
        value: https://api.yourdomain.com # Replace with your actual API URL
      - key: APP_SECRET
        generateValue: true